# Generated by Django 3.1 on 2020-09-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('son_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
    ]
