# Generated by Django 3.1 on 2020-09-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('son_blog', '0002_auto_20200927_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resumo',
            new_name='summary',
        ),
    ]
